//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankaFisiExcelAktarim.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ISvc")]
    public interface ISvc {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISvc/AppendDataObject", ReplyAction="http://tempuri.org/ISvc/AppendDataObjectResponse")]
        BankaFisiExcelAktarim.ServiceReference1.AppendDataObjectResponse AppendDataObject(BankaFisiExcelAktarim.ServiceReference1.AppendDataObjectRequest request);
        
        // CODEGEN: İşlemin birden fazla dönüş değeri olduğundan ileti sözleşmesi oluşturuluyor.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISvc/AppendDataObject", ReplyAction="http://tempuri.org/ISvc/AppendDataObjectResponse")]
        System.Threading.Tasks.Task<BankaFisiExcelAktarim.ServiceReference1.AppendDataObjectResponse> AppendDataObjectAsync(BankaFisiExcelAktarim.ServiceReference1.AppendDataObjectRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISvc/ReadDataObject", ReplyAction="http://tempuri.org/ISvc/ReadDataObjectResponse")]
        BankaFisiExcelAktarim.ServiceReference1.ReadDataObjectResponse ReadDataObject(BankaFisiExcelAktarim.ServiceReference1.ReadDataObjectRequest request);
        
        // CODEGEN: İşlemin birden fazla dönüş değeri olduğundan ileti sözleşmesi oluşturuluyor.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISvc/ReadDataObject", ReplyAction="http://tempuri.org/ISvc/ReadDataObjectResponse")]
        System.Threading.Tasks.Task<BankaFisiExcelAktarim.ServiceReference1.ReadDataObjectResponse> ReadDataObjectAsync(BankaFisiExcelAktarim.ServiceReference1.ReadDataObjectRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISvc/ReadDataObjectXML", ReplyAction="http://tempuri.org/ISvc/ReadDataObjectXMLResponse")]
        BankaFisiExcelAktarim.ServiceReference1.ReadDataObjectXMLResponse ReadDataObjectXML(BankaFisiExcelAktarim.ServiceReference1.ReadDataObjectXMLRequest request);
        
        // CODEGEN: İşlemin birden fazla dönüş değeri olduğundan ileti sözleşmesi oluşturuluyor.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISvc/ReadDataObjectXML", ReplyAction="http://tempuri.org/ISvc/ReadDataObjectXMLResponse")]
        System.Threading.Tasks.Task<BankaFisiExcelAktarim.ServiceReference1.ReadDataObjectXMLResponse> ReadDataObjectXMLAsync(BankaFisiExcelAktarim.ServiceReference1.ReadDataObjectXMLRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISvc/DeleteDataObject", ReplyAction="http://tempuri.org/ISvc/DeleteDataObjectResponse")]
        BankaFisiExcelAktarim.ServiceReference1.DeleteDataObjectResponse DeleteDataObject(BankaFisiExcelAktarim.ServiceReference1.DeleteDataObjectRequest request);
        
        // CODEGEN: İşlemin birden fazla dönüş değeri olduğundan ileti sözleşmesi oluşturuluyor.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISvc/DeleteDataObject", ReplyAction="http://tempuri.org/ISvc/DeleteDataObjectResponse")]
        System.Threading.Tasks.Task<BankaFisiExcelAktarim.ServiceReference1.DeleteDataObjectResponse> DeleteDataObjectAsync(BankaFisiExcelAktarim.ServiceReference1.DeleteDataObjectRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISvc/CalculateDataObject", ReplyAction="http://tempuri.org/ISvc/CalculateDataObjectResponse")]
        BankaFisiExcelAktarim.ServiceReference1.CalculateDataObjectResponse CalculateDataObject(BankaFisiExcelAktarim.ServiceReference1.CalculateDataObjectRequest request);
        
        // CODEGEN: İşlemin birden fazla dönüş değeri olduğundan ileti sözleşmesi oluşturuluyor.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISvc/CalculateDataObject", ReplyAction="http://tempuri.org/ISvc/CalculateDataObjectResponse")]
        System.Threading.Tasks.Task<BankaFisiExcelAktarim.ServiceReference1.CalculateDataObjectResponse> CalculateDataObjectAsync(BankaFisiExcelAktarim.ServiceReference1.CalculateDataObjectRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISvc/ExecQuery", ReplyAction="http://tempuri.org/ISvc/ExecQueryResponse")]
        BankaFisiExcelAktarim.ServiceReference1.ExecQueryResponse ExecQuery(BankaFisiExcelAktarim.ServiceReference1.ExecQueryRequest request);
        
        // CODEGEN: İşlemin birden fazla dönüş değeri olduğundan ileti sözleşmesi oluşturuluyor.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISvc/ExecQuery", ReplyAction="http://tempuri.org/ISvc/ExecQueryResponse")]
        System.Threading.Tasks.Task<BankaFisiExcelAktarim.ServiceReference1.ExecQueryResponse> ExecQueryAsync(BankaFisiExcelAktarim.ServiceReference1.ExecQueryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISvc/DirectQuery", ReplyAction="http://tempuri.org/ISvc/DirectQueryResponse")]
        BankaFisiExcelAktarim.ServiceReference1.DirectQueryResponse DirectQuery(BankaFisiExcelAktarim.ServiceReference1.DirectQueryRequest request);
        
        // CODEGEN: İşlemin birden fazla dönüş değeri olduğundan ileti sözleşmesi oluşturuluyor.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISvc/DirectQuery", ReplyAction="http://tempuri.org/ISvc/DirectQueryResponse")]
        System.Threading.Tasks.Task<BankaFisiExcelAktarim.ServiceReference1.DirectQueryResponse> DirectQueryAsync(BankaFisiExcelAktarim.ServiceReference1.DirectQueryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISvc/getValue", ReplyAction="http://tempuri.org/ISvc/getValueResponse")]
        BankaFisiExcelAktarim.ServiceReference1.getValueResponse getValue(BankaFisiExcelAktarim.ServiceReference1.getValueRequest request);
        
        // CODEGEN: İşlemin birden fazla dönüş değeri olduğundan ileti sözleşmesi oluşturuluyor.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISvc/getValue", ReplyAction="http://tempuri.org/ISvc/getValueResponse")]
        System.Threading.Tasks.Task<BankaFisiExcelAktarim.ServiceReference1.getValueResponse> getValueAsync(BankaFisiExcelAktarim.ServiceReference1.getValueRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISvc/getTableName", ReplyAction="http://tempuri.org/ISvc/getTableNameResponse")]
        string getTableName(int TableNr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISvc/getTableName", ReplyAction="http://tempuri.org/ISvc/getTableNameResponse")]
        System.Threading.Tasks.Task<string> getTableNameAsync(int TableNr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISvc/printDoc", ReplyAction="http://tempuri.org/ISvc/printDocResponse")]
        void printDoc(short doctype, int docRef, string termCode, string designTitle, string printerCode, short printCnt, string securityCode, string LbsLoadPass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISvc/printDoc", ReplyAction="http://tempuri.org/ISvc/printDocResponse")]
        System.Threading.Tasks.Task printDocAsync(short doctype, int docRef, string termCode, string designTitle, string printerCode, short printCnt, string securityCode, string LbsLoadPass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISvc/getInfo", ReplyAction="http://tempuri.org/ISvc/getInfoResponse")]
        BankaFisiExcelAktarim.ServiceReference1.getInfoResponse getInfo(BankaFisiExcelAktarim.ServiceReference1.getInfoRequest request);
        
        // CODEGEN: İşlemin birden fazla dönüş değeri olduğundan ileti sözleşmesi oluşturuluyor.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISvc/getInfo", ReplyAction="http://tempuri.org/ISvc/getInfoResponse")]
        System.Threading.Tasks.Task<BankaFisiExcelAktarim.ServiceReference1.getInfoResponse> getInfoAsync(BankaFisiExcelAktarim.ServiceReference1.getInfoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AppendDataObject", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AppendDataObjectRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int dataType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int dataReference;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string dataXML;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string paramXML;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string errorString;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public byte status;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public string LbsLoadPass;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        public int FirmNr;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=8)]
        public string securityCode;
        
        public AppendDataObjectRequest() {
        }
        
        public AppendDataObjectRequest(int dataType, int dataReference, string dataXML, string paramXML, string errorString, byte status, string LbsLoadPass, int FirmNr, string securityCode) {
            this.dataType = dataType;
            this.dataReference = dataReference;
            this.dataXML = dataXML;
            this.paramXML = paramXML;
            this.errorString = errorString;
            this.status = status;
            this.LbsLoadPass = LbsLoadPass;
            this.FirmNr = FirmNr;
            this.securityCode = securityCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AppendDataObjectResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AppendDataObjectResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int dataReference;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string dataXML;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string paramXML;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string errorString;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public byte status;
        
        public AppendDataObjectResponse() {
        }
        
        public AppendDataObjectResponse(int dataReference, string dataXML, string paramXML, string errorString, byte status) {
            this.dataReference = dataReference;
            this.dataXML = dataXML;
            this.paramXML = paramXML;
            this.errorString = errorString;
            this.status = status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadDataObject", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ReadDataObjectRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int dataType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int dataReference;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string dataXML;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string paramXML;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string errorString;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public byte status;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public string LbsLoadPass;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        public int FirmNr;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=8)]
        public string securityCode;
        
        public ReadDataObjectRequest() {
        }
        
        public ReadDataObjectRequest(int dataType, int dataReference, string dataXML, string paramXML, string errorString, byte status, string LbsLoadPass, int FirmNr, string securityCode) {
            this.dataType = dataType;
            this.dataReference = dataReference;
            this.dataXML = dataXML;
            this.paramXML = paramXML;
            this.errorString = errorString;
            this.status = status;
            this.LbsLoadPass = LbsLoadPass;
            this.FirmNr = FirmNr;
            this.securityCode = securityCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadDataObjectResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ReadDataObjectResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int dataReference;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string dataXML;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string paramXML;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string errorString;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public byte status;
        
        public ReadDataObjectResponse() {
        }
        
        public ReadDataObjectResponse(int dataReference, string dataXML, string paramXML, string errorString, byte status) {
            this.dataReference = dataReference;
            this.dataXML = dataXML;
            this.paramXML = paramXML;
            this.errorString = errorString;
            this.status = status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadDataObjectXML", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ReadDataObjectXMLRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int dataType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int dataReference;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string dataXML;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string paramXML;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string errorString;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public byte status;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public string LbsLoadPass;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        public int FirmNr;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=8)]
        public string securityCode;
        
        public ReadDataObjectXMLRequest() {
        }
        
        public ReadDataObjectXMLRequest(int dataType, int dataReference, string dataXML, string paramXML, string errorString, byte status, string LbsLoadPass, int FirmNr, string securityCode) {
            this.dataType = dataType;
            this.dataReference = dataReference;
            this.dataXML = dataXML;
            this.paramXML = paramXML;
            this.errorString = errorString;
            this.status = status;
            this.LbsLoadPass = LbsLoadPass;
            this.FirmNr = FirmNr;
            this.securityCode = securityCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadDataObjectXMLResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ReadDataObjectXMLResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int dataReference;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string dataXML;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string paramXML;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string errorString;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public byte status;
        
        public ReadDataObjectXMLResponse() {
        }
        
        public ReadDataObjectXMLResponse(int dataReference, string dataXML, string paramXML, string errorString, byte status) {
            this.dataReference = dataReference;
            this.dataXML = dataXML;
            this.paramXML = paramXML;
            this.errorString = errorString;
            this.status = status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteDataObject", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DeleteDataObjectRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int dataType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int dataReference;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string errorString;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public byte status;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string LbsLoadPass;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public int FirmNr;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public string securityCode;
        
        public DeleteDataObjectRequest() {
        }
        
        public DeleteDataObjectRequest(int dataType, int dataReference, string errorString, byte status, string LbsLoadPass, int FirmNr, string securityCode) {
            this.dataType = dataType;
            this.dataReference = dataReference;
            this.errorString = errorString;
            this.status = status;
            this.LbsLoadPass = LbsLoadPass;
            this.FirmNr = FirmNr;
            this.securityCode = securityCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteDataObjectResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DeleteDataObjectResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string errorString;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public byte status;
        
        public DeleteDataObjectResponse() {
        }
        
        public DeleteDataObjectResponse(string errorString, byte status) {
            this.errorString = errorString;
            this.status = status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CalculateDataObject", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CalculateDataObjectRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int dataType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int dataReference;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string dataXML;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string paramXML;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string errorString;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public byte status;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public string LbsLoadPass;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        public int FirmNr;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=8)]
        public string securityCode;
        
        public CalculateDataObjectRequest() {
        }
        
        public CalculateDataObjectRequest(int dataType, int dataReference, string dataXML, string paramXML, string errorString, byte status, string LbsLoadPass, int FirmNr, string securityCode) {
            this.dataType = dataType;
            this.dataReference = dataReference;
            this.dataXML = dataXML;
            this.paramXML = paramXML;
            this.errorString = errorString;
            this.status = status;
            this.LbsLoadPass = LbsLoadPass;
            this.FirmNr = FirmNr;
            this.securityCode = securityCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CalculateDataObjectResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CalculateDataObjectResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int dataReference;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string dataXML;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string paramXML;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string errorString;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public byte status;
        
        public CalculateDataObjectResponse() {
        }
        
        public CalculateDataObjectResponse(int dataReference, string dataXML, string paramXML, string errorString, byte status) {
            this.dataReference = dataReference;
            this.dataXML = dataXML;
            this.paramXML = paramXML;
            this.errorString = errorString;
            this.status = status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExecQuery", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ExecQueryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string sqlText;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string orderByText;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string securityCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public object resultXML;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string errorString;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public byte status;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public string LbsLoadPass;
        
        public ExecQueryRequest() {
        }
        
        public ExecQueryRequest(string sqlText, string orderByText, string securityCode, object resultXML, string errorString, byte status, string LbsLoadPass) {
            this.sqlText = sqlText;
            this.orderByText = orderByText;
            this.securityCode = securityCode;
            this.resultXML = resultXML;
            this.errorString = errorString;
            this.status = status;
            this.LbsLoadPass = LbsLoadPass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExecQueryResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ExecQueryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public object resultXML;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string errorString;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public byte status;
        
        public ExecQueryResponse() {
        }
        
        public ExecQueryResponse(object resultXML, string errorString, byte status) {
            this.resultXML = resultXML;
            this.errorString = errorString;
            this.status = status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DirectQuery", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DirectQueryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string sqlText;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string securityCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string errorString;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public byte status;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string LbsLoadPass;
        
        public DirectQueryRequest() {
        }
        
        public DirectQueryRequest(string sqlText, string securityCode, string errorString, byte status, string LbsLoadPass) {
            this.sqlText = sqlText;
            this.securityCode = securityCode;
            this.errorString = errorString;
            this.status = status;
            this.LbsLoadPass = LbsLoadPass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DirectQueryResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DirectQueryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string errorString;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public byte status;
        
        public DirectQueryResponse() {
        }
        
        public DirectQueryResponse(string errorString, byte status) {
            this.errorString = errorString;
            this.status = status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getValue", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getValueRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public short Flag;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int Value;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public bool isFlag;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string securityCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string LbsLoadPass;
        
        public getValueRequest() {
        }
        
        public getValueRequest(short Flag, int Value, bool isFlag, string securityCode, string LbsLoadPass) {
            this.Flag = Flag;
            this.Value = Value;
            this.isFlag = isFlag;
            this.securityCode = securityCode;
            this.LbsLoadPass = LbsLoadPass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getValueResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getValueResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int Value;
        
        public getValueResponse() {
        }
        
        public getValueResponse(int Value) {
            this.Value = Value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getInfo", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public object resultXML;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string securityCode;
        
        public getInfoRequest() {
        }
        
        public getInfoRequest(object resultXML, string securityCode) {
            this.resultXML = resultXML;
            this.securityCode = securityCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getInfoResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public object resultXML;
        
        public getInfoResponse() {
        }
        
        public getInfoResponse(object resultXML) {
            this.resultXML = resultXML;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISvcChannel : BankaFisiExcelAktarim.ServiceReference1.ISvc, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SvcClient : System.ServiceModel.ClientBase<BankaFisiExcelAktarim.ServiceReference1.ISvc>, BankaFisiExcelAktarim.ServiceReference1.ISvc {
        
        public SvcClient() {
        }
        
        public SvcClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SvcClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SvcClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SvcClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BankaFisiExcelAktarim.ServiceReference1.AppendDataObjectResponse BankaFisiExcelAktarim.ServiceReference1.ISvc.AppendDataObject(BankaFisiExcelAktarim.ServiceReference1.AppendDataObjectRequest request) {
            return base.Channel.AppendDataObject(request);
        }
        
        public void AppendDataObject(int dataType, ref int dataReference, ref string dataXML, ref string paramXML, ref string errorString, ref byte status, string LbsLoadPass, int FirmNr, string securityCode) {
            BankaFisiExcelAktarim.ServiceReference1.AppendDataObjectRequest inValue = new BankaFisiExcelAktarim.ServiceReference1.AppendDataObjectRequest();
            inValue.dataType = dataType;
            inValue.dataReference = dataReference;
            inValue.dataXML = dataXML;
            inValue.paramXML = paramXML;
            inValue.errorString = errorString;
            inValue.status = status;
            inValue.LbsLoadPass = LbsLoadPass;
            inValue.FirmNr = FirmNr;
            inValue.securityCode = securityCode;
            BankaFisiExcelAktarim.ServiceReference1.AppendDataObjectResponse retVal = ((BankaFisiExcelAktarim.ServiceReference1.ISvc)(this)).AppendDataObject(inValue);
            dataReference = retVal.dataReference;
            dataXML = retVal.dataXML;
            paramXML = retVal.paramXML;
            errorString = retVal.errorString;
            status = retVal.status;
        }
        
        public System.Threading.Tasks.Task<BankaFisiExcelAktarim.ServiceReference1.AppendDataObjectResponse> AppendDataObjectAsync(BankaFisiExcelAktarim.ServiceReference1.AppendDataObjectRequest request) {
            return base.Channel.AppendDataObjectAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BankaFisiExcelAktarim.ServiceReference1.ReadDataObjectResponse BankaFisiExcelAktarim.ServiceReference1.ISvc.ReadDataObject(BankaFisiExcelAktarim.ServiceReference1.ReadDataObjectRequest request) {
            return base.Channel.ReadDataObject(request);
        }
        
        public void ReadDataObject(int dataType, ref int dataReference, ref string dataXML, ref string paramXML, ref string errorString, ref byte status, string LbsLoadPass, int FirmNr, string securityCode) {
            BankaFisiExcelAktarim.ServiceReference1.ReadDataObjectRequest inValue = new BankaFisiExcelAktarim.ServiceReference1.ReadDataObjectRequest();
            inValue.dataType = dataType;
            inValue.dataReference = dataReference;
            inValue.dataXML = dataXML;
            inValue.paramXML = paramXML;
            inValue.errorString = errorString;
            inValue.status = status;
            inValue.LbsLoadPass = LbsLoadPass;
            inValue.FirmNr = FirmNr;
            inValue.securityCode = securityCode;
            BankaFisiExcelAktarim.ServiceReference1.ReadDataObjectResponse retVal = ((BankaFisiExcelAktarim.ServiceReference1.ISvc)(this)).ReadDataObject(inValue);
            dataReference = retVal.dataReference;
            dataXML = retVal.dataXML;
            paramXML = retVal.paramXML;
            errorString = retVal.errorString;
            status = retVal.status;
        }
        
        public System.Threading.Tasks.Task<BankaFisiExcelAktarim.ServiceReference1.ReadDataObjectResponse> ReadDataObjectAsync(BankaFisiExcelAktarim.ServiceReference1.ReadDataObjectRequest request) {
            return base.Channel.ReadDataObjectAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BankaFisiExcelAktarim.ServiceReference1.ReadDataObjectXMLResponse BankaFisiExcelAktarim.ServiceReference1.ISvc.ReadDataObjectXML(BankaFisiExcelAktarim.ServiceReference1.ReadDataObjectXMLRequest request) {
            return base.Channel.ReadDataObjectXML(request);
        }
        
        public void ReadDataObjectXML(int dataType, ref int dataReference, ref string dataXML, ref string paramXML, ref string errorString, ref byte status, string LbsLoadPass, int FirmNr, string securityCode) {
            BankaFisiExcelAktarim.ServiceReference1.ReadDataObjectXMLRequest inValue = new BankaFisiExcelAktarim.ServiceReference1.ReadDataObjectXMLRequest();
            inValue.dataType = dataType;
            inValue.dataReference = dataReference;
            inValue.dataXML = dataXML;
            inValue.paramXML = paramXML;
            inValue.errorString = errorString;
            inValue.status = status;
            inValue.LbsLoadPass = LbsLoadPass;
            inValue.FirmNr = FirmNr;
            inValue.securityCode = securityCode;
            BankaFisiExcelAktarim.ServiceReference1.ReadDataObjectXMLResponse retVal = ((BankaFisiExcelAktarim.ServiceReference1.ISvc)(this)).ReadDataObjectXML(inValue);
            dataReference = retVal.dataReference;
            dataXML = retVal.dataXML;
            paramXML = retVal.paramXML;
            errorString = retVal.errorString;
            status = retVal.status;
        }
        
        public System.Threading.Tasks.Task<BankaFisiExcelAktarim.ServiceReference1.ReadDataObjectXMLResponse> ReadDataObjectXMLAsync(BankaFisiExcelAktarim.ServiceReference1.ReadDataObjectXMLRequest request) {
            return base.Channel.ReadDataObjectXMLAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BankaFisiExcelAktarim.ServiceReference1.DeleteDataObjectResponse BankaFisiExcelAktarim.ServiceReference1.ISvc.DeleteDataObject(BankaFisiExcelAktarim.ServiceReference1.DeleteDataObjectRequest request) {
            return base.Channel.DeleteDataObject(request);
        }
        
        public void DeleteDataObject(int dataType, int dataReference, ref string errorString, ref byte status, string LbsLoadPass, int FirmNr, string securityCode) {
            BankaFisiExcelAktarim.ServiceReference1.DeleteDataObjectRequest inValue = new BankaFisiExcelAktarim.ServiceReference1.DeleteDataObjectRequest();
            inValue.dataType = dataType;
            inValue.dataReference = dataReference;
            inValue.errorString = errorString;
            inValue.status = status;
            inValue.LbsLoadPass = LbsLoadPass;
            inValue.FirmNr = FirmNr;
            inValue.securityCode = securityCode;
            BankaFisiExcelAktarim.ServiceReference1.DeleteDataObjectResponse retVal = ((BankaFisiExcelAktarim.ServiceReference1.ISvc)(this)).DeleteDataObject(inValue);
            errorString = retVal.errorString;
            status = retVal.status;
        }
        
        public System.Threading.Tasks.Task<BankaFisiExcelAktarim.ServiceReference1.DeleteDataObjectResponse> DeleteDataObjectAsync(BankaFisiExcelAktarim.ServiceReference1.DeleteDataObjectRequest request) {
            return base.Channel.DeleteDataObjectAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BankaFisiExcelAktarim.ServiceReference1.CalculateDataObjectResponse BankaFisiExcelAktarim.ServiceReference1.ISvc.CalculateDataObject(BankaFisiExcelAktarim.ServiceReference1.CalculateDataObjectRequest request) {
            return base.Channel.CalculateDataObject(request);
        }
        
        public void CalculateDataObject(int dataType, ref int dataReference, ref string dataXML, ref string paramXML, ref string errorString, ref byte status, string LbsLoadPass, int FirmNr, string securityCode) {
            BankaFisiExcelAktarim.ServiceReference1.CalculateDataObjectRequest inValue = new BankaFisiExcelAktarim.ServiceReference1.CalculateDataObjectRequest();
            inValue.dataType = dataType;
            inValue.dataReference = dataReference;
            inValue.dataXML = dataXML;
            inValue.paramXML = paramXML;
            inValue.errorString = errorString;
            inValue.status = status;
            inValue.LbsLoadPass = LbsLoadPass;
            inValue.FirmNr = FirmNr;
            inValue.securityCode = securityCode;
            BankaFisiExcelAktarim.ServiceReference1.CalculateDataObjectResponse retVal = ((BankaFisiExcelAktarim.ServiceReference1.ISvc)(this)).CalculateDataObject(inValue);
            dataReference = retVal.dataReference;
            dataXML = retVal.dataXML;
            paramXML = retVal.paramXML;
            errorString = retVal.errorString;
            status = retVal.status;
        }
        
        public System.Threading.Tasks.Task<BankaFisiExcelAktarim.ServiceReference1.CalculateDataObjectResponse> CalculateDataObjectAsync(BankaFisiExcelAktarim.ServiceReference1.CalculateDataObjectRequest request) {
            return base.Channel.CalculateDataObjectAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BankaFisiExcelAktarim.ServiceReference1.ExecQueryResponse BankaFisiExcelAktarim.ServiceReference1.ISvc.ExecQuery(BankaFisiExcelAktarim.ServiceReference1.ExecQueryRequest request) {
            return base.Channel.ExecQuery(request);
        }
        
        public void ExecQuery(string sqlText, string orderByText, string securityCode, ref object resultXML, ref string errorString, ref byte status, string LbsLoadPass) {
            BankaFisiExcelAktarim.ServiceReference1.ExecQueryRequest inValue = new BankaFisiExcelAktarim.ServiceReference1.ExecQueryRequest();
            inValue.sqlText = sqlText;
            inValue.orderByText = orderByText;
            inValue.securityCode = securityCode;
            inValue.resultXML = resultXML;
            inValue.errorString = errorString;
            inValue.status = status;
            inValue.LbsLoadPass = LbsLoadPass;
            BankaFisiExcelAktarim.ServiceReference1.ExecQueryResponse retVal = ((BankaFisiExcelAktarim.ServiceReference1.ISvc)(this)).ExecQuery(inValue);
            resultXML = retVal.resultXML;
            errorString = retVal.errorString;
            status = retVal.status;
        }
        
        public System.Threading.Tasks.Task<BankaFisiExcelAktarim.ServiceReference1.ExecQueryResponse> ExecQueryAsync(BankaFisiExcelAktarim.ServiceReference1.ExecQueryRequest request) {
            return base.Channel.ExecQueryAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BankaFisiExcelAktarim.ServiceReference1.DirectQueryResponse BankaFisiExcelAktarim.ServiceReference1.ISvc.DirectQuery(BankaFisiExcelAktarim.ServiceReference1.DirectQueryRequest request) {
            return base.Channel.DirectQuery(request);
        }
        
        public void DirectQuery(string sqlText, string securityCode, ref string errorString, ref byte status, string LbsLoadPass) {
            BankaFisiExcelAktarim.ServiceReference1.DirectQueryRequest inValue = new BankaFisiExcelAktarim.ServiceReference1.DirectQueryRequest();
            inValue.sqlText = sqlText;
            inValue.securityCode = securityCode;
            inValue.errorString = errorString;
            inValue.status = status;
            inValue.LbsLoadPass = LbsLoadPass;
            BankaFisiExcelAktarim.ServiceReference1.DirectQueryResponse retVal = ((BankaFisiExcelAktarim.ServiceReference1.ISvc)(this)).DirectQuery(inValue);
            errorString = retVal.errorString;
            status = retVal.status;
        }
        
        public System.Threading.Tasks.Task<BankaFisiExcelAktarim.ServiceReference1.DirectQueryResponse> DirectQueryAsync(BankaFisiExcelAktarim.ServiceReference1.DirectQueryRequest request) {
            return base.Channel.DirectQueryAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BankaFisiExcelAktarim.ServiceReference1.getValueResponse BankaFisiExcelAktarim.ServiceReference1.ISvc.getValue(BankaFisiExcelAktarim.ServiceReference1.getValueRequest request) {
            return base.Channel.getValue(request);
        }
        
        public void getValue(short Flag, ref int Value, bool isFlag, string securityCode, string LbsLoadPass) {
            BankaFisiExcelAktarim.ServiceReference1.getValueRequest inValue = new BankaFisiExcelAktarim.ServiceReference1.getValueRequest();
            inValue.Flag = Flag;
            inValue.Value = Value;
            inValue.isFlag = isFlag;
            inValue.securityCode = securityCode;
            inValue.LbsLoadPass = LbsLoadPass;
            BankaFisiExcelAktarim.ServiceReference1.getValueResponse retVal = ((BankaFisiExcelAktarim.ServiceReference1.ISvc)(this)).getValue(inValue);
            Value = retVal.Value;
        }
        
        public System.Threading.Tasks.Task<BankaFisiExcelAktarim.ServiceReference1.getValueResponse> getValueAsync(BankaFisiExcelAktarim.ServiceReference1.getValueRequest request) {
            return base.Channel.getValueAsync(request);
        }
        
        public string getTableName(int TableNr) {
            return base.Channel.getTableName(TableNr);
        }
        
        public System.Threading.Tasks.Task<string> getTableNameAsync(int TableNr) {
            return base.Channel.getTableNameAsync(TableNr);
        }
        
        public void printDoc(short doctype, int docRef, string termCode, string designTitle, string printerCode, short printCnt, string securityCode, string LbsLoadPass) {
            base.Channel.printDoc(doctype, docRef, termCode, designTitle, printerCode, printCnt, securityCode, LbsLoadPass);
        }
        
        public System.Threading.Tasks.Task printDocAsync(short doctype, int docRef, string termCode, string designTitle, string printerCode, short printCnt, string securityCode, string LbsLoadPass) {
            return base.Channel.printDocAsync(doctype, docRef, termCode, designTitle, printerCode, printCnt, securityCode, LbsLoadPass);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BankaFisiExcelAktarim.ServiceReference1.getInfoResponse BankaFisiExcelAktarim.ServiceReference1.ISvc.getInfo(BankaFisiExcelAktarim.ServiceReference1.getInfoRequest request) {
            return base.Channel.getInfo(request);
        }
        
        public void getInfo(ref object resultXML, string securityCode) {
            BankaFisiExcelAktarim.ServiceReference1.getInfoRequest inValue = new BankaFisiExcelAktarim.ServiceReference1.getInfoRequest();
            inValue.resultXML = resultXML;
            inValue.securityCode = securityCode;
            BankaFisiExcelAktarim.ServiceReference1.getInfoResponse retVal = ((BankaFisiExcelAktarim.ServiceReference1.ISvc)(this)).getInfo(inValue);
            resultXML = retVal.resultXML;
        }
        
        public System.Threading.Tasks.Task<BankaFisiExcelAktarim.ServiceReference1.getInfoResponse> getInfoAsync(BankaFisiExcelAktarim.ServiceReference1.getInfoRequest request) {
            return base.Channel.getInfoAsync(request);
        }
    }
}
